# Generated by Django 5.1.6 on 2025-03-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonesreciclatge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='cod',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
