# Generated by Django 5.1.6 on 2025-03-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonesreciclatge', '0002_contenedor_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contenedor',
            name='tipus',
            field=models.CharField(choices=[('paper', 'Paper'), ('plàstic', 'Plàstic'), ('vidre', 'Vidre'), ('orgànic', 'Orgànic'), ('rebuig', 'Rebuig')], max_length=100),
        ),
    ]
