# Generated by Django 5.1.6 on 2025-05-05 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonesreciclatge', '0003_alter_contenedor_tipus'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contenedor',
            name='alerta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='fecha_ultimo_vaciado',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='motivo_alerta',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contenedor',
            name='ultima_revision',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='ReporteContenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('mal_estado', 'Contenedor en mal estado'), ('lleno', 'Contenedor lleno'), ('vandalismo', 'Vandalismo'), ('ubicacion', 'Problema con la ubicación'), ('olores', 'Malos olores'), ('otro', 'Otro problema')], max_length=50)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='reportes/')),
                ('estado', models.CharField(choices=[('abierto', 'Abierto'), ('en_proceso', 'En proceso'), ('resuelto', 'Resuelto'), ('rechazado', 'Rechazado')], default='abierto', max_length=50)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('comentario_cierre', models.TextField(blank=True, null=True)),
                ('contenedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='zonesreciclatge.contenedor')),
                ('gestor_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_asignados', to=settings.AUTH_USER_MODEL)),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_resueltos', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_enviados', to=settings.AUTH_USER_MODEL)),
                ('zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes', to='zonesreciclatge.zonesreciclatge')),
            ],
            options={
                'verbose_name_plural': 'Reportes de contenedores',
                'ordering': ['-fecha'],
                'permissions': [('can_manage_reports', 'Puede gestionar reportes')],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('reporte', 'Nuevo reporte'), ('contenedor_estado', 'Cambio de estado'), ('contenedor_lleno', 'Contenedor lleno'), ('contenedor_mal_estado', 'Contenedor en mal estado'), ('sistema', 'Mensaje del sistema')], max_length=50)),
                ('titulo', models.CharField(max_length=100)),
                ('mensaje', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('leida', models.BooleanField(default=False)),
                ('relacion_contenedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zonesreciclatge.contenedor')),
                ('relacion_zona', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zonesreciclatge.zonesreciclatge')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
                ('relacion_reporte', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zonesreciclatge.reportecontenedor')),
            ],
            options={
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='HistorialContenedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('estado_anterior', models.CharField(choices=[('buit', 'Buit'), ('ple', 'Ple'), ('mig', 'Mig ple')], max_length=100)),
                ('estado_actual', models.CharField(choices=[('buit', 'Buit'), ('ple', 'Ple'), ('mig', 'Mig ple')], max_length=100)),
                ('nivel_llenado', models.IntegerField(blank=True, help_text='Porcentaje de llenado (0-100)', null=True)),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('contenedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='zonesreciclatge.contenedor')),
            ],
            options={
                'verbose_name_plural': 'Historial de contenedores',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['contenedor', 'fecha'], name='zonesrecicl_contene_b33d5a_idx')],
            },
        ),
    ]
