# Generated by Django 5.1.6 on 2025-05-06 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_email_alter_customuser_empresa'),
        ('zonesreciclatge', '0004_contenedor_alerta_contenedor_fecha_ultimo_vaciado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportecontenedor',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reportes', to='accounts.empresa'),
        ),
    ]
