# Generated by Django 5.1.6 on 2025-05-15 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonesreciclatge', '0005_reportecontenedor_empresa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecontenedor',
            name='estado',
            field=models.CharField(choices=[('abierto', 'Obert'), ('en_proceso', 'En procés'), ('resuelto', 'Resolt'), ('rechazado', 'Rebutjat')], default='abierto', max_length=50),
        ),
        migrations.AlterField(
            model_name='reportecontenedor',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baixa'), ('media', 'Mitjana'), ('alta', 'Alta'), ('urgente', 'Urgent')], default='media', max_length=50),
        ),
        migrations.AlterField(
            model_name='reportecontenedor',
            name='tipo',
            field=models.CharField(choices=[('mal_estado', 'Contenidor en mal estat'), ('lleno', 'Contenidor ple'), ('vandalismo', 'Vandalisme'), ('ubicacion', 'Problema amb la ubicació'), ('olores', 'Mals olors'), ('otro', 'Altre problema')], max_length=50),
        ),
        migrations.CreateModel(
            name='ComentarioReporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('reporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='zonesreciclatge.reportecontenedor')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comentarios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha'],
            },
        ),
    ]
