# Generated by Django 5.1.6 on 2025-05-15 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonesreciclatge', '0006_alter_reportecontenedor_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarioreporte',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='comentarios_reportes/'),
        ),
    ]
