# Generated by Django 5.1.6 on 2025-05-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zonesreciclatge', '0007_comentarioreporte_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportecontenedor',
            name='tipo',
            field=models.CharField(choices=[('mal_estado', 'Contenidor en mal estat'), ('lleno', 'Contenidor ple'), ('vandalismo', 'Vandalisme'), ('ubicacion', 'Problema amb la ubicació'), ('olores', 'Mals olors'), ('falta_contenedor', 'Falta un contenidor'), ('otro', 'Altre problema')], max_length=50),
        ),
    ]
