# Generated by Django 5.1.6 on 2025-03-14 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_empresa_customuser_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='CP',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
