# Generated by Django 5.1.6 on 2025-05-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_customuser_email_alter_customuser_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='tickets_rechazados_acumulados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ultima_penalizacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ultimo_ticket_rechazado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
