# Generated by Django 5.1.6 on 2025-05-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_tickets_rechazados_acumulados_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='total_score',
            field=models.IntegerField(default=0),
        ),
    ]
