# Generated by Django 5.1.6 on 2025-05-20 07:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('color', models.CharField(default='#000000', max_length=7)),
                ('puntos', models.IntegerField(default=10)),
                ('contenedor', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materials',
            },
        ),
        migrations.CreateModel(
            name='ProductoReciclado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_barras', models.CharField(max_length=50)),
                ('nombre_producto', models.CharField(blank=True, max_length=255, null=True)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('imagen_url', models.URLField(blank=True, null=True)),
                ('fecha_reciclaje', models.DateTimeField(auto_now_add=True)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='sistema_reciclatge.material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_reciclados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Producte Reciclat',
                'verbose_name_plural': 'Productes Reciclats',
                'ordering': ['-fecha_reciclaje'],
            },
        ),
    ]
