# Generated by Django 5.1.6 on 2025-05-20 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_reciclatge', '0001_initial'),
        ('zonesreciclatge', '0007_comentarioreporte_imagen'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BolsaVirtual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_reciclaje', models.DateTimeField(blank=True, null=True)),
                ('reciclada', models.BooleanField(default=False)),
                ('puntos_totales', models.IntegerField(default=0)),
                ('contenedor_reciclaje', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='zonesreciclatge.contenedor')),
                ('tipo_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsas', to='sistema_reciclatge.material')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolsas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='productoreciclado',
            name='bolsa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='sistema_reciclatge.bolsavirtual'),
        ),
    ]
