# Generated by Django 5.1.6 on 2025-05-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema_reciclatge', '0004_standardize_material_types'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bolsavirtual',
            options={'verbose_name': 'Bossa Virtual', 'verbose_name_plural': 'Bosses Virtuals'},
        ),
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(choices=[('paper', 'Paper/Cartró'), ('plàstic', 'Plàstic'), ('vidre', 'Vidre'), ('orgànic', 'Orgànic'), ('rebuig', 'Rebuig'), ('indiferenciat', 'Indiferenciat')], max_length=100),
        ),
    ]
