# Generated by Django 5.1.6 on 2025-05-21 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_customuser_tickets_rechazados_acumulados_and_more'),
        ('sistema_reciclatge', '0005_alter_bolsavirtual_options_alter_material_nombre'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='nombre',
            field=models.CharField(choices=[('plàstic', 'Plàstic'), ('paper', 'Paper/Cartró'), ('vidre', 'Vidre'), ('orgànic', 'Orgànic'), ('rebuig', 'Rebuig'), ('indiferenciat', 'Indiferenciat')], max_length=100),
        ),
        migrations.CreateModel(
            name='Prize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='prizes/')),
                ('puntos_costo', models.PositiveIntegerField()),
                ('cantidad', models.PositiveIntegerField(default=0)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prizes_created', to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prizes', to='accounts.empresa')),
            ],
            options={
                'verbose_name': 'Premi',
                'verbose_name_plural': 'Premis',
            },
        ),
        migrations.CreateModel(
            name='PrizeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_redencion', models.DateTimeField(auto_now_add=True)),
                ('puntos_gastados', models.PositiveIntegerField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendent de lliurament'), ('procesando', 'En procés'), ('entregado', 'Lliurat'), ('cancelado', 'Cancel·lat')], default='pendiente', max_length=20)),
                ('codigo_confirmacion', models.CharField(blank=True, max_length=20, null=True)),
                ('notas', models.TextField(blank=True)),
                ('premio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='sistema_reciclatge.prize')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Redempció de Premi',
                'verbose_name_plural': 'Redempcions de Premis',
                'ordering': ['-fecha_redencion'],
            },
        ),
    ]
